language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - "pip install coveralls"
  - "pip install -e .[test]"
script: 
  - py.test
  - coverage run --source=xt -m py.test
after_success:
  - coveralls
sudo: false
deploy:
  on:
    repo: mapbox/xt
    python: 3.8
    tags: true
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: __token__
